# Generated by Django 3.1.5 on 2021-03-09 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Artefact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.PositiveIntegerField(default=0, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=50)),
                ('Project_Description', models.TextField()),
                ('Upload_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Approval_Date', models.DateTimeField(blank=True, null=True)),
                ('Last_Updated', models.DateTimeField(blank=True, null=True)),
                ('Project_Approval_Status', models.CharField(choices=[('Apvd', 'Approved'), ('Pndg', 'Pending'), ('Rjct', 'Rejected')], default='Pndg', max_length=32)),
                ('Authors', models.CharField(max_length=100)),
                ('User_Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.userprofileinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Artefact_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtefactType', models.CharField(choices=[('Vid', 'Video'), ('Pic', 'Picture')], max_length=50)),
                ('ArtefactName', models.CharField(max_length=50)),
                ('ArtefactSize', models.CharField(max_length=50)),
                ('Project_Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.project')),
            ],
        ),
    ]
