# Generated by Django 3.1.5 on 2021-01-31 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Username', models.CharField(max_length=50)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('StudentID', models.PositiveIntegerField(unique=True)),
                ('Date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Account_Status', models.CharField(choices=[('Act', 'Active'), ('P', 'Pending'), ('T', 'Terminated')], default='Act', max_length=50)),
                ('Last_Online', models.DateTimeField()),
            ],
        ),
    ]
