# Generated by Django 3.1.5 on 2021-01-31 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=50)),
                ('Project_Description', models.TextField()),
                ('Upload_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Approval_Date', models.DateTimeField()),
                ('Last_Updated', models.DateTimeField()),
                ('Authors', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
