# Generated by Django 3.1.5 on 2021-01-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20210131_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_Approval_Status',
            field=models.CharField(choices=[('Apvd', 'Approved'), ('Pndg', 'Pending'), ('Rjct', 'Rejected')], default='Pndg', max_length=32),
        ),
    ]
