# Generated by Django 3.1.5 on 2021-01-31 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_login_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtefactType', models.CharField(choices=[('Vid', 'Video'), ('Pic', 'Picture')], max_length=50)),
                ('ArtefactName', models.CharField(max_length=50)),
                ('ArtefactSize', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='Approval_Date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Last_Updated',
        ),
        migrations.CreateModel(
            name='Project_Artefact_Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artefact_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.artefact_info')),
                ('Project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.project')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Project_Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.project')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.user')),
            ],
        ),
    ]
