# Generated by Django 3.1.5 on 2021-01-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_auto_20210131_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Approval_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Last_Updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
