# Generated by Django 3.1.5 on 2021-02-08 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_auto_20210131_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Last_Online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
