# Generated by Django 3.1.5 on 2021-02-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_remove_userprofileinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='account_project_connector',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.userprofileinfo'),
        ),
        migrations.AlterField(
            model_name='login_credential',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.userprofileinfo'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
