# Generated by Django 3.1.5 on 2021-02-08 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_auto_20210208_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Username', models.CharField(max_length=50, unique=True)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('StudentID', models.PositiveIntegerField(unique=True)),
                ('Date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Account_Status', models.CharField(choices=[('Act', 'Active'), ('P', 'Pending'), ('T', 'Terminated')], default='Act', max_length=50)),
                ('Last_Online', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='account_project_connector',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.user'),
        ),
        migrations.AlterField(
            model_name='login_credential',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.user'),
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
