# Generated by Django 3.1.5 on 2021-02-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_auto_20210208_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='StudentID',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
