# Generated by Django 3.1.5 on 2021-02-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0016_delete_login_credential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_User',
        ),
    ]
